// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testconnsvr.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "testconnsvr.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace testConnSvr_Conf {

namespace {

const ::google::protobuf::Descriptor* testConnSvrCfg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  testConnSvrCfg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_testconnsvr_2eproto() {
  protobuf_AddDesc_testconnsvr_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "testconnsvr.proto");
  GOOGLE_CHECK(file != NULL);
  testConnSvrCfg_descriptor_ = file->message_type(0);
  static const int testConnSvrCfg_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testConnSvrCfg, port_),
  };
  testConnSvrCfg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      testConnSvrCfg_descriptor_,
      testConnSvrCfg::default_instance_,
      testConnSvrCfg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testConnSvrCfg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testConnSvrCfg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(testConnSvrCfg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_testconnsvr_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    testConnSvrCfg_descriptor_, &testConnSvrCfg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_testconnsvr_2eproto() {
  delete testConnSvrCfg::default_instance_;
  delete testConnSvrCfg_reflection_;
}

void protobuf_AddDesc_testconnsvr_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021testconnsvr.proto\022\020testConnSvr_Conf\"\036\n"
    "\016testConnSvrCfg\022\014\n\004port\030\001 \002(\007", 69);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "testconnsvr.proto", &protobuf_RegisterTypes);
  testConnSvrCfg::default_instance_ = new testConnSvrCfg();
  testConnSvrCfg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_testconnsvr_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_testconnsvr_2eproto {
  StaticDescriptorInitializer_testconnsvr_2eproto() {
    protobuf_AddDesc_testconnsvr_2eproto();
  }
} static_descriptor_initializer_testconnsvr_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int testConnSvrCfg::kPortFieldNumber;
#endif  // !_MSC_VER

testConnSvrCfg::testConnSvrCfg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void testConnSvrCfg::InitAsDefaultInstance() {
}

testConnSvrCfg::testConnSvrCfg(const testConnSvrCfg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void testConnSvrCfg::SharedCtor() {
  _cached_size_ = 0;
  port_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

testConnSvrCfg::~testConnSvrCfg() {
  SharedDtor();
}

void testConnSvrCfg::SharedDtor() {
  if (this != default_instance_) {
  }
}

void testConnSvrCfg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* testConnSvrCfg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return testConnSvrCfg_descriptor_;
}

const testConnSvrCfg& testConnSvrCfg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_testconnsvr_2eproto();
  return *default_instance_;
}

testConnSvrCfg* testConnSvrCfg::default_instance_ = NULL;

testConnSvrCfg* testConnSvrCfg::New() const {
  return new testConnSvrCfg;
}

void testConnSvrCfg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    port_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool testConnSvrCfg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 port = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void testConnSvrCfg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required fixed32 port = 1;
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->port(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* testConnSvrCfg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required fixed32 port = 1;
  if (has_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->port(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int testConnSvrCfg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 port = 1;
    if (has_port()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void testConnSvrCfg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const testConnSvrCfg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const testConnSvrCfg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void testConnSvrCfg::MergeFrom(const testConnSvrCfg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_port()) {
      set_port(from.port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void testConnSvrCfg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void testConnSvrCfg::CopyFrom(const testConnSvrCfg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool testConnSvrCfg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void testConnSvrCfg::Swap(testConnSvrCfg* other) {
  if (other != this) {
    std::swap(port_, other->port_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata testConnSvrCfg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = testConnSvrCfg_descriptor_;
  metadata.reflection = testConnSvrCfg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace testConnSvr_Conf

// @@protoc_insertion_point(global_scope)
